package com.example.thisi.applicationx;

import java.math.BigDecimal;

public class Suspend {
    public String COMPANY_CODE;
    public String OUTLET_CODE;
    public String POS_NO;
    public String SHIFT_NO;
    public String RCP_NO;
    public String TRANS_TYPE;
    public String	BUS_DATE;
    public String	TRANS_DATE;
    public String TRANS_TIME;
    public int ROW_NUMBER;
    public String PROD_CODE;
    public String BARCODE;
    public String PROD_NAME;
    public String PROD_SHORT_NAME;
    public String PROD_TYPE_CODE;
    public String USAGE_UOM;
    public BigDecimal UOM_CONV;
    public BigDecimal QUANTITY;
    public String PRICE_LVL_CODE;
    public BigDecimal UNIT_PRICE;
    public BigDecimal TOTAL_PRICE;
    public String BOM_PARENT;
    public BigDecimal TAX_01;
    public BigDecimal TAX_02;
    public BigDecimal TAX_03;
    public BigDecimal TAX_04;
    public BigDecimal TAX_05;
    public boolean ALLOW_DISC;
    public boolean MULTIPLE_DISC;
    public String DISCOUNT_CODE;
    public BigDecimal ITEM_DISCOUNT_AMOUNT;
    public String TOTAL_DICOUNT_CODE;
    public BigDecimal TOTAL_DISCOUNT_AMOUNT;
    public BigDecimal TICKET_SURCHARGE;
    public String STAFF_DISCOUNT_CODE;
    public BigDecimal STAFF_DISCOUNT;
    public String SUSPEND_NUMBER;
    public boolean IsRECALL;
    public boolean IS_UPSALES;
    public BigDecimal UPSALES_CONV;
    public boolean IS_MULTIPLEUOM;
    public String RECALL_BY;
    public String APPROVE_BY;
    public String MODIFIED_DATE;
    public String MODIFIED_ID;
    public String CUSTOMER_CODE;
    public String TAXCODE;
    public BigDecimal COST;
    public String PRICE_GRP_CODE;
    public String TABLE_NO;
    public String PROMOSOURCECODE;
    public BigDecimal PROMOCHANGEPRICE;
}